## Basic Configuration
baseurl = "https://www.mattmayes.com/"
languageCode = "en"

title = "Matt Mayes from Chicago, IL"
theme = "hyde-hyde-mateo"

## Hugo Built-in Features
# disqusShortname = "matt-mayes"
googleAnalytics = "UA-27793526-1"
enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    author = "Matt"
    title = "Matt Mayes from Chicago"
    description = "Chicago, IL"
    metaDescription = "Matt lives in Chicago and likes tech, music, and bbq."
    # jpg and webp must exist!
    authorimage = "/img/matt-brussels-400"
    dateformat = "Jan 2, 2006"
    postNavigation = false

    # sidebar, copyright & license
    # copyright = "htr3n"
    # license = "CC BY-SA 4.0"
    # licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    # showBuiltWith = true

    # https://highlightjs.org
    # highlightjs = true
    # highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

    customCss = ["scss/custom.scss"]

## Social Accounts
[params.social]
    github = "stoptime"
    instagram = "m_mayes"
    twitter = "stoptime"
    linkedin = "mattamayes"
    email = "mattamayes at gmail"

## Main Menu
[[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 50
    url = "/"
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
## [[menu.main]]
##     name = "Resume"
##     identifier = "portfolio"
##     weight = 200
##     url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
[[menu.main]]
    name = "Jazz Conspiracy"
    identifier = "jazzconspiracy"
    weight = 300
    url = "/jazzconspiracy/"
[[menu.main]]
    name = "Ether Frolics"
    identifier = "etherfrolics"
    weight = 300
    url = "/etherfrolics/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
